apiVersion: v1
kind: ReplicationController
metadata:
  name: backend 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tier: backend 
    spec:
      containers:
      - name: nginx 
        image: caseydavenport/nginx 
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80 
