apiVersion: v1
kind: ReplicationController
metadata:
  name: calico-policy-agent
  namespace: kube-system 
  labels:
    version: v0.1.0
    projectcalico.org/app: "policy-agent"
spec:
  replicas: 1
  selector:
    version: v0.1.0
    projectcalico.org/app: "policy-agent"
  template:
    metadata:
      labels:
        version: v0.1.0
        projectcalico.org/app: "policy-agent"
    spec:
      containers:
        - name: policyagent
          image: calico/k8s-policy-agent
          imagePollPolicy: always
          env:
          - name: ETCD_AUTHORITY
            value: "<KUBERNETES_MASTER>:2379"
          - name: K8S_API
            value: "https://10.100.0.1"
          - name: K8S_AUTH_TOKEN
            value: "<TOKEN>"
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
