apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: calico-policy-agent
  namespace: calico-system 
  labels:
    version: v0.1.0
    projectcalico.org/app: "policy-agent"
spec:
  replicas: 1
  selector:
    version: v0.1.0
    projectcalico.org/app: "policy-agent"
  template:
    metadata:
      labels:
        version: v0.1.0
        projectcalico.org/app: "policy-agent"
    spec:
      containers:
        - name: policyagent
          image: caseydavenport/k8s-policy-agent
          imagePullPolicy: Always
          env:
          - name: ETCD_AUTHORITY
            value: "<ETCD_HOST>:<ETCD_PORT>"
