kind: NetworkPolicy
apiVersion: net.alpha.kubernetes.io/v1alpha1
metadata:
  name: test-policy
  namespace: default
podSelector:
  tier: backend
ingress:
  - ports:
    - port: 80
      protocol: TCP
    from: 
    - pods:
       tier: middle
    - pods:
       role: test
